=== data-fair/data-fair/server/misc/utils/dcat/schema/catalog.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "https://project-open-data.cio.gov/v1.1/schema/catalog.json#",
  "title": "Project Open Data Catalog",
  "description": "Validates an entire collection of Project Open Data metadata JSON objects. Agencies produce said collections in the form of Data.json files.",
  "type": "object",
  "dependencies": {
    "@type": [
      "@context"
    ]
  },
  "required": [
    "conformsTo",
    "dataset"
  ],
  "properties": {
    "@context": {
      "title": "Metadata Context",
      "description": "URL or JSON object for the JSON-LD Context that defines the schema used"
    },
    "@id": {
      "title": "Metadata Catalog ID",
      "description": "IRI for the JSON-LD Node Identifier of the Catalog. This should be the URL of the data.json file itself.",
      "type": "string",
      "format": "uri"
    },
    "@type": {
      "title": "Metadata Context",
      "description": "IRI for the JSON-LD data type. This should be dcat:Catalog for the Catalog",
      "enum": [
        "dcat:Catalog",
        "Catalog"
      ]
    },
    "conformsTo": {
      "description": "Version of Schema",
      "title": "Version of Schema",
      "enum": [
        "https://project-open-data.cio.gov/v1.1/schema"
      ]
    },
    "describedBy": {
      "description": "URL for the JSON Schema file that defines the schema used",
      "title": "Data Dictionary",
      "type": "string",
      "format": "uri"
    },
    "dataset": {
      "type": "array",
      "items": {
        "$ref": "dataset.json",
        "minItems": 1,
        "uniqueItems": true
      }
    },
    "modified": {
      "title": "Last Update",
      "description": "Most recent date on which the catalog was changed, updated or modified.",
      "anyOf": [
        {
          "type": "string",
          "pattern": "^([\\+-]?\\d{4}(?!\\d{2}\\b))((-?)((0[1-9]|1[0-2])(\\3([12]\\d|0[1-9]|3[01]))?|W([0-4]\\d|5[0-2])(-?[1-7])?|(00[1-9]|0[1-9]\\d|[12]\\d{2}|3([0-5]\\d|6[1-6])))([T\\s]((([01]\\d|2[0-3])((:?)[0-5]\\d)?|24\\:?00)([\\.,]\\d+(?!:))?)?(\\17[0-5]\\d([\\.,]\\d+)?)?([zZ]|([\\+-])([01]\\d|2[0-3]):?([0-5]\\d)?)?)?)?$"
        },
        {
          "type": "string",
          "pattern": "^(R\\d*\\/)?P(?:\\d+(?:\\.\\d+)?Y)?(?:\\d+(?:\\.\\d+)?M)?(?:\\d+(?:\\.\\d+)?W)?(?:\\d+(?:\\.\\d+)?D)?(?:T(?:\\d+(?:\\.\\d+)?H)?(?:\\d+(?:\\.\\d+)?M)?(?:\\d+(?:\\.\\d+)?S)?)?$"
        },
        {
          "type": "string",
          "pattern": "^(R\\d*\\/)?([\\+-]?\\d{4}(?!\\d{2}\\b))((-?)((0[1-9]|1[0-2])(\\4([12]\\d|0[1-9]|3[01]))?|W([0-4]\\d|5[0-2])(-?[1-7])?|(00[1-9]|0[1-9]\\d|[12]\\d{2}|3([0-5]\\d|6[1-6])))([T\\s]((([01]\\d|2[0-3])((:?)[0-5]\\d)?|24\\:?00)([\\.,]\\d+(?!:))?)?(\\18[0-5]\\d([\\.,]\\d+)?)?([zZ]|([\\+-])([01]\\d|2[0-3]):?([0-5]\\d)?)?)?)?(\\/)P(?:\\d+(?:\\.\\d+)?Y)?(?:\\d+(?:\\.\\d+)?M)?(?:\\d+(?:\\.\\d+)?W)?(?:\\d+(?:\\.\\d+)?D)?(?:T(?:\\d+(?:\\.\\d+)?H)?(?:\\d+(?:\\.\\d+)?M)?(?:\\d+(?:\\.\\d+)?S)?)?$"
        }
      ]
    },
    "description": {
      "title": "Description",
      "type": "string",
      "minLength": 1
    }
  }
}

=== data-fair/data-fair/test/resources/dcat/example-cio.json
{
  "@context": "https://project-open-data.cio.gov/v1.1/schema/catalog.jsonld",
  "@type": "Catalog",
  "conformsTo": "https://project-open-data.cio.gov/v1.1/schema",
  "describedBy": "https://project-open-data.cio.gov/v1.1/schema/catalog.json",
  "modified": "2022-05-10T00:00:00+00:00",
  "dataset": [
    {
      "@type": "Dataset",
      "identifier": "3d1a9c4636fd4419a09eefa1f79f6291",
      "license": "Licence Ouverte v2.0",
      "title": "Dataset 1",
      "description": "Description dataset 1.",
      "keyword": [
        "keyword1",
        "keyword2"
      ],
      "temporal": "2021-01-01T00:00:00+00:00/2021-12-31T00:00:00+00:00",
      "accrualPeriodicity": "http://purl.org/cld/freq/daily",
      "modified": "2022-05-10T00:00:00+00:00",
      "distribution": [
        {
          "@type": "Distribution",
          "identifier": "830db87ea997498bb20d033ace3fe6dd",
          "title": "dataset1.csv",
          "format": "csv",
          "mediaType": "text/csv",
          "downloadURL": "https://test.com/dataset1.csv",
          "modified": "2022-05-10T00:00:00+00:00"
        }
      ],
      "publisher": {
        "@type": "org:Organization",
        "name": "Organization 1"
      },
      "contactPoint": {
        "@type": "vcard:Contact",
        "fn": "Test Contact",
        "hasEmail": "mailto:contact@test.com"
      },
      "accessLevel": "non-public"
    },
    {
      "@type": "Dataset",
      "identifier": "a4566ff6dab74c6eba780ac51c22a468",
      "license": "Licence Ouverte v2.0",
      "title": "Dataset 2",
      "description": "Description **dataset 2**.",
      "keyword": [
        "keyword1",
        "keyword3"
      ],
      "accrualPeriodicity": "http://purl.org/cld/freq/triennial",
      "modified": "2022-05-10T00:00:00+00:00",
      "distribution": [
        {
          "@type": "Distribution",
          "identifier": "ac4c77dd793d45228c7b22a8a79f9126",
          "title": "Dataset 2 geojson",
          "format": "geojson",
          "mediaType": "application/geo+json",
          "downloadURL": "https://test.com/dataset2.geojson"
        },
        {
          "@type": "Distribution",
          "identifier": "5300f12395444c92ad4a774e0c4f70ee",
          "title": "Dataset 2 csv",
          "format": "csv",
          "mediaType": "text/csv",
          "downloadURL": "https://test.com/dataset2.csv"
        }
      ],
      "publisher": {
        "@type": "org:Organization",
        "name": "Organization 1"
      },
      "contactPoint": {
        "@type": "vcard:Contact",
        "fn": "Test Contact",
        "hasEmail": "mailto:contact@test.com"
      },
      "accessLevel": "public"
    }
  ]
}
